# mecanum plugin odometry
- ros_topic_name: "/<robot_name>/chassis_odometry_gt"
  gz_topic_name: "/model/<robot_name>/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: "GZ_TO_ROS"

# JointStatePublisher publish
- ros_topic_name: "/<robot_name>/joint_states"
  gz_topic_name: "/world/default/model/<robot_name>/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/imu"
  gz_topic_name: "/world/default/model/<robot_name>/link/d435i/sensor/imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/color/image"
  gz_topic_name: "/world/default/model/<robot_name>/link/d435i/sensor/color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/color/camera_info"
  gz_topic_name: "/world/default/model/<robot_name>/link/d435i/sensor/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/infra1/image"
  gz_topic_name: "/world/default/model/<robot_name>/link/infra1_frame/sensor/infra1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/infra1/camera_info"
  gz_topic_name: "/world/default/model/<robot_name>/link/infra1_frame/sensor/infra1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/infra2/image"
  gz_topic_name: "/world/default/model/<robot_name>/link/infra2_frame/sensor/infra2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/infra2/camera_info"
  gz_topic_name: "/world/default/model/<robot_name>/link/infra2_frame/sensor/infra2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/d435i/depth/depth_image/points"
  gz_topic_name: "/world/default/model/<robot_name>/link/d435i/sensor/depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

# - ros_topic_name: "/<robot_name>/d435i/depth/camera_info"
#   gz_topic_name: "/world/default/model/<robot_name>/link/d435i/sensor/depth/camera_info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "ignition.msgs.CameraInfo"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/<robot_name>/d435i/depth/depth_image"
#   gz_topic_name: "/world/default/model/<robot_name>/link/d435i/sensor/depth/depth_image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/livox/lidar"
  gz_topic_name: "/world/default/model/<robot_name>/link/mid360/sensor/mid360_lidar/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/livox/imu"
  gz_topic_name: "/world/default/model/<robot_name>/link/mid360/sensor/mid360_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/<robot_name>/cmd_vel"
  gz_topic_name: "/model/<robot_name>/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"

