# mecanum plugin odometry
- ros_topic_name: "/chassis_odometry_gt"
  gz_topic_name: "/model/wheelchair/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: "GZ_TO_ROS"

# JointStatePublisher publish
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/default/model/wheelchair/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/imu"
  gz_topic_name: "/world/default/model/wheelchair/link/left_d435i/sensor/left_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/depth/image"
  gz_topic_name: "/world/default/model/wheelchair/link/left_d435i/sensor/left_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/depth/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/left_d435i/sensor/left_depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/depth/depth_image/points"
  gz_topic_name: "/world/default/model/wheelchair/link/left_d435i/sensor/left_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/color/image"
  gz_topic_name: "/world/default/model/wheelchair/link/left_d435i/sensor/left_color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/color/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/left_d435i/sensor/left_color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/infra1/image"
  gz_topic_name: "/world/default/model/wheelchair/link/left_infra1_frame/sensor/left_infra1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/infra1/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/left_infra1_frame/sensor/left_infra1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/infra2/image"
  gz_topic_name: "/world/default/model/wheelchair/link/left_infra2_frame/sensor/left_infra2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_d435i/infra2/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/left_infra2_frame/sensor/left_infra2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/imu"
  gz_topic_name: "/world/default/model/wheelchair/link/right_d435i/sensor/right_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/depth/image"
  gz_topic_name: "/world/default/model/wheelchair/link/right_d435i/sensor/right_depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/depth/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/right_d435i/sensor/right_depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/depth/depth_image/points"
  gz_topic_name: "/world/default/model/wheelchair/link/right_d435i/sensor/right_depth/depth_image/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/color/image"
  gz_topic_name: "/world/default/model/wheelchair/link/right_d435i/sensor/right_color/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/color/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/right_d435i/sensor/right_color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/infra1/image"
  gz_topic_name: "/world/default/model/wheelchair/link/right_infra1_frame/sensor/right_infra1/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/infra1/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/right_infra1_frame/sensor/right_infra1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/infra2/image"
  gz_topic_name: "/world/default/model/wheelchair/link/right_infra2_frame/sensor/right_infra2/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_d435i/infra2/camera_info"
  gz_topic_name: "/world/default/model/wheelchair/link/right_infra2_frame/sensor/right_infra2/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/livox/lidar"
  gz_topic_name: "/world/default/model/wheelchair/link/mid360/sensor/mid360_lidar/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/livox/imu"
  gz_topic_name: "/world/default/model/wheelchair/link/mid360/sensor/mid360_imu/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/wheelchair/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: "ROS_TO_GZ"

